### ISSUE TITLE
removing the current text and replacing with a placeholder

### ISSUE THREAD

**Issue by dbeigi** [wajeehsheikh/Waj-Notes#4]
Hey @wajeehsheikh I was looking at your project and it looks great, especially with the background. One thing i think that will improve your application is removing the current text displayed in your editable area and placing a placeholder so the user doesn't have to remove the current text. I'll try to fix this for you.

**Comment by wajeehsheikh** [comment]
I appreciate the help.

Thank you 
Wajeeh
