### ISSUE TITLE
Clearing and Saving Functions

### ISSUE THREAD

**Issue by Manan311** [wajeehsheikh/Waj-Notes#6]
Hi Wajeeh,

I would like to add a saving note and clearing note buttons as well as a shortcut for clearing the notepad. I will also like to update the <h3>"Write freely and press ctrl+s to save your work. Enjoy! :)"</h3> to also inform the user of the clear shortcut as well if that fine.

Thank You,
Manan

**Comment by wajeehsheikh** [comment]
Hi Manan,

That would be great. I can't wait to see the changes.

Thank you,
Wajeeh
